language: python

sudo: required
dist: xenial

matrix:
  include:
    - python: 3.7
      env: TOXENV=py,codecov
    - python: 3.6
      env: TOXENV=py,codecov
    - python: 3.5
      env: TOXENV=py,codecov

install: 
  - pip install tox

script: tox
